using Test

include("test_package.jl")
include("test_derive_params.jl")
include("test_flexible_system.jl")
include("test_flexible_solver.jl")
include("test_analysis_helpers.jl")
include("test_modal_decomposition.jl")
include("test_root_tracing.jl")
include("test_migration.jl")
include("test_sweep.jl")
include("test_video.jl")
include("test_optimization_objective.jl")
include("test_optimization_gradients.jl")
include("test_graded_beam_params.jl")
include("test_thrust_sxx_agreement.jl")
include("test_edge_bc_physics.jl")
include("test_system_residual.jl")
include("test_beam_bcs.jl")
include("test_symmetry.jl")
